sudo: required
services:
  - docker

before_install:
  - docker build -t jsur/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true jsur/docker-prod-workflow npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-prod-workflow"
  env: "DockerProdWorkflow-env"
  bucket_name: "elasticbeanstalk-eu-central-1-566312720731"
  bucket_path: "docker-prod-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"