sudo: required
services:
  - docker

before_install:
  - docker build -t jsur/docker-prod-workflow -f Dockerfile.dev .

script:
  - docker run -e CI=true jsur/docker-prod-workflow npm run test -- --coverage --watchAll=false