version: '3'
services:
  web:
    build:
    # context says where all the files and directories will be pulled from
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app